"""

Revision ID: 140ad55bf206
Revises: 456af2375d92
Create Date: 2026-05-19 04:02:06.221121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140ad55bf206'
down_revision = '456af2375d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
