"""init

Revision ID: 456af2375d92
Revises: 
Create Date: 2026-05-19 03:59:29.538283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456af2375d92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
